# Generated by Django 4.0.5 on 2022-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
    ]
